### ISSUE TITLE
有个小问题咨询一下，关于Bootstrap目录

### ISSUE THREAD

**Issue by jia-github-pro** [maemual/MSI-B460M-10700-5500XT#11]
作者您好，感谢分享，有个问题想咨询一下，oc0.6.6以后，官方版本已经移除了Bootstrap启动保护机制，您这个0.6.8里面怎么还有相关的内容？

**Comment by maemual** [comment]
哦，没注意这个，是从低版本一步一步升上来的，没注意去掉了。

**Comment by maemual** [comment]
已删除。
