### ISSUE TITLE
同款网卡隔空投送稳定吗？

### ISSUE THREAD

**Issue by abnerxc** [maemual/MSI-B460M-10700-5500XT#18]

**Comment by abnerxc** [comment]
10次测试 能有1-2次发现

**Comment by maemual** [comment]
挺正常的，没遇到啥问题。不过因为网卡自带的天线在机箱后面，放在书房里信号不太好，我就自己换了一个天线的延长线出来。这种的。
![IMG_0385](https://user-images.githubusercontent.com/2352843/122319243-eddec680-cf52-11eb-8540-cddcbca8591f.JPG)

不知道有没有啥影响。你可以距离天线比较近的地方测试看是不是有好转？

**Comment by abnerxc** [comment]
好的，我试试
