### ISSUE TITLE
睡眠问题

### ISSUE THREAD

**Issue by LonelyDeShadow** [maemual/MSI-B460M-10700-5500XT#22]
你好，我有一套跟你差不多的配置，主要是处理器和机箱不一样，都是十代。
你的黑苹果睡眠后会有电源隔段时间被唤醒的情况吗，电源唤醒后风扇、硬盘会转，但屏幕不会启动，半分钟左右自己就关掉了。

**Comment by maemual** [comment]
有发现过。

**Comment by maemual** [comment]
感觉可能是开着电能小憩有关吧。🤔️

**Comment by LonelyDeShadow** [comment]
> 感觉可能是开着电能小憩有关吧。🤔️

我试了一下，电能小憩关掉之后似乎没有这个问题了。
看到有评论说oc出过一个解决这个问题的补丁
