### ISSUE TITLE
bios有几个找不到,配置与你一模一样

### ISSUE THREAD

**Issue by Elijah-Guo** [maemual/MSI-B460M-10700-5500XT#3]
顺便问下，安装的镜像从哪里下的,可以咨询下么，我wx 16619710998

**Comment by maemual** [comment]
OpenCore 的文档上都有写，在 Mac 系统上可以直接通过 App Store 下载，或者通过一个通用的脚本，在各个系统平台上都可以手工下载指定需要的版本。

**Comment by maemual** [comment]
@Elijah-Guo https://github.com/szc188/MSI-B460M-MORTAR-10700K-5500XT-OC#bios%E8%AE%BE%E7%BD%AE
BIOS 可以看看这个，这个贴了图，多找找。
