### ISSUE TITLE
10500 + 5600XT 需要改什么？

### ISSUE THREAD

**Issue by tlerbao** [maemual/MSI-B460M-10700-5500XT#30]

**Comment by maemual** [comment]
应该不用改啥。

**Comment by tlerbao** [comment]
@maemual 我配置 B460M + 10500+5600XT+ 32G内存 ，测试了一下您的EFI，发现蓝牙无法使用；请问怎么解决呢？

**Comment by maemual** [comment]
硬件是 Fenvi FV-T919 BCM94360CD 吗？

**Comment by tlerbao** [comment]
@maemual 硬件不是这个牌子的，我hackintool把我之前的efi的usb定制导出覆盖你的USBPorts.kext，蓝牙可以用了，应该就是usb定制的问题。

我之前用的https://github.com/myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630这个efi，最近两个版本偶尔会死机（虽然频率很低），所以考虑还你的看看哈哈 。感谢你们造轮子。

**Comment by maemual** [comment]
👍 蓝牙是插在 usb header 上的，确实会和 USBPorts.kext 相关。
