### ISSUE TITLE
本想学你自己做套EFI

### ISSUE THREAD

**Issue by tlerbao** [maemual/MSI-B460M-10700-5500XT#31]
根据 OpenCore Install Guide 和你的说明，用最新的0.7.5，其他文件也是最新的，最后文件和你几乎一样，只有USB定制文件不一样，config.plist 先是原版教程走一遍不行，对照您的改了改还是不行，启动就报，不知道是什么问题哈。
![image](https://user-images.githubusercontent.com/20442232/140923188-002b2159-cbb6-45a6-b19f-65f360cc89e6.png)

**Comment by maemual** [comment]
SSD 是啥？看网上有个讨论，好像有点关系？

https://github.com/xxxzc/xps15-9550-macos/issues/74

里面有一些修复方案，可以参考看看？
