### ISSUE TITLE
你好，蓝牙不可用，如何单独自己配置 USBPorts.kext 来正确处理 USB Map 的问题？

### ISSUE THREAD

**Issue by SuvanCheng** [maemual/MSI-B460M-10700-5500XT#44]

**Comment by maemual** [comment]
可以看看 https://www.bilibili.com/video/BV1Aa4y1j7CL?spm_id_from=333.999.0.0 司波图的教程

**Comment by SuvanCheng** [comment]
谢谢你的回复～

我按照斯波图的教程尝试了好几次，始终无法显示蓝牙usb（hackintool里面不现实蓝牙usb），
我把之前EFI中的aml放进来（就像斯波图那样的两个aml文件，加入plist里面），也删掉了USBPorts.kext，然后电脑就无法开机了。


为了使用蓝牙，我有换回[旧版EFI](https://github.com/myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630)，蓝牙一切正常，就是OC版本旧了点儿，final cut pro 用起来非常卡顿，你的EFI final cut pro 就飞起。（如果你有空，可以告诉我一个升级OC引导版本的链接，我去学习学习）。

谢谢你的查看～

**Comment by maemual** [comment]
升级 OC 可以看看这个文档 https://dortania.github.io/OpenCore-Post-Install/universal/update.html

主要的流程其实就是：
1. 下载最新版的 oc
2. 以下修改 U盘 里的 oc 配置
3. 更新 OpenCore 的三个基础文件
4. 用 OCConfigCompare 这样的工具对比当前使用的 config.plist 和最新版的 Sample.plist
5. 按照 Differences.pdf 看看不一样的配置项的含义，一般绝大部分情况下，直接使用 Sample.plist 的配置就可以了
6. 修改完保存，然后使用 u 盘启动
7. 启动起来之后看看有没有什么异常，用 hackintool 看看
8. 没啥问题的话，把 U盘里的配置，覆盖电脑硬盘里的 efi
9. 重启

**Comment by WeiJinglun** [comment]
hackintool 里面不显示蓝牙，或者你可以升级一下 hackintool

**Comment by SuvanCheng** [comment]
感谢@WeiJinglun 的建议，我尝试了最新版的hackintool，依然不显示蓝牙设备。

> hackintool 里面不显示蓝牙，或者你可以升级一下 hackintool


但是我发现有两个unknown一直绿着，我就设置为内建，导出了USBPorts.kext，然后替换作者的USBPorts.kext，重启后，发现蓝牙可用了！！！但是内建显示的是usb2.0设备和灯条控制。

![image](https://user-images.githubusercontent.com/24319035/166098778-029dc33c-ceb8-427e-b74f-f34239e8ef16.png)


感谢 @maemual 提供的方法，第一次没成功是我自己没有认真尝试，🥹

> 可以看看 https://www.bilibili.com/video/BV1Aa4y1j7CL?spm_id_from=333.999.0.0 司波图的教程

现在蓝牙已经OK啦～，谢谢～
