### ISSUE TITLE
主板选择微星 MSI MAG B460M MORTAR WIFI版本会有问题吗？

### ISSUE THREAD

**Issue by juststrive007** [maemual/MSI-B460M-10700-5500XT#7]
主板选择微星 MSI MAG B460M MORTAR WIFI版本，自带的WIFI模块不用，会不会有影响

**Comment by juststrive007** [comment]
已经测试，不会影响，主板自带的WiFi6不会被驱动，无任何影响。

**Comment by fred-mk** [comment]
> 已经测试，不会影响，主板自带的WiFi6不会被驱动，无任何影响。

还在折腾黑苹果吗？我跟你一样的主板，但是会经常卡死，你会有这个问题 吗？

**Comment by juststrive007** [comment]
> 
没有遇到卡死的现象，你看下是不是bios配置的问题
