### ISSUE TITLE
没显卡 核显可以嘛

### ISSUE THREAD

**Issue by evan-xie** [maemual/MSI-B460M-10700-5500XT#8]
没显卡 核显可以嘛

**Comment by maemual** [comment]
可以搞，但是可能会遇到一些小问题，主要看 AAPL,ig-platform-id 那块的参数。

**Comment by evan-xie** [comment]
<dict>
				<key>AAPL,ig-platform-id</key>
				<data>AwDImw==</data>
			</dict>
这一段删除嘛

**Comment by maemual** [comment]
你看一下 opencore 的文档，这里是需要换一个参数
https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#add-2
